{
 "title": "ContainersMonitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Servers",
    "query": "show tag values from cpu with key=host"
   }
  ]
 },
 "panels": [
  {
   "title": "$Servers machine Total Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$Servers machine Total Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$Servers machine Total Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$Servers machine Total Containers Images",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$Servers Machine Containers Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "uptime_ns" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$Servers machine containers memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Servers$/" }
     ]
    }
   ]
  }
 ]
}